# Generated by Django 4.2.2 on 2023-06-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("IN", models.DecimalField(decimal_places=2, max_digits=8)),
                ("OUT", models.DecimalField(decimal_places=2, max_digits=8)),
                ("image", models.ImageField(upload_to="pics")),
                ("sat", models.IntegerField()),
            ],
        ),
    ]
